version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: rmart_postgres
    environment:
      POSTGRES_DB: DB_Rmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

volumes:
  postgres_data: